version: 2.1

orbs:
  cit: chime/ci-tools@dev:6c46477

jobs:
  build:
    docker:
      - image: cimg/ruby:2.7-node
    steps:
      - checkout
      - cit/sonarcloud-scan



workflows:
  main:
    jobs:
      - build:
          context: SonarCloud
